apiVersion: v1
kind: Secret
metadata:
  name: cms-secret
  namespace: cms
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/cms_blog"
  REDIS_URL: "redis://redis:6379"
  JWT_SECRET: "super-secret-key-change-me"
